server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://120.55.165.85:3306/cloud_order?useSSL=false
    username: root
    password: '!520Bm1121'
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: SZ
#        namespace: df05fe98-38a1-452f-bf9d-a6715b01dcfc
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS